-- 02_CORE_TABLES_CREATION.SQL (HOTFIX V70.2)
-- Purpose: Create missing core tables and implement unified RLS lockdown.

-- 0. HELPER FUNCTION (FIXED: Uses id = auth.uid())
CREATE OR REPLACE FUNCTION get_my_family_id() 
RETURNS UUID AS $$
  SELECT family_id FROM public.profiles WHERE id = auth.uid() LIMIT 1;
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- 1. ALERTS TABLE
CREATE TABLE IF NOT EXISTS public.alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL, -- 'fall', 'speeding', 'heart_rate', 'weather'
  severity TEXT CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  status TEXT DEFAULT 'active', -- 'active', 'acknowledged', 'resolved'
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. VITALS_LOG TABLE
CREATE TABLE IF NOT EXISTS public.vitals_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  heart_rate TEXT,
  blood_pressure TEXT,
  logged_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. MEDICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.medications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  dosage TEXT,
  schedule TEXT NOT NULL, -- e.g., '12:00 PM'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. MEDICATION_LOGS TABLE
CREATE TABLE IF NOT EXISTS public.medication_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medication_id UUID REFERENCES public.medications(id) ON DELETE CASCADE NOT NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  taken_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  status TEXT DEFAULT 'taken' -- 'taken', 'missed', 'snoozed'
);

-- 5. MANAGED_DEVICES TABLE
CREATE TABLE IF NOT EXISTS public.managed_devices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  assigned_profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  device_type TEXT NOT NULL, -- 'apple_watch', 'nanit_cam', 'bp_cuff'
  last_ping TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- PHASE 2: INTEGRATED RLS LOCKDOWN
-- ==========================================

-- Enable RLS on all new tables
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vitals_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medication_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.managed_devices ENABLE ROW LEVEL SECURITY;

-- 1. Alerts Policy
DROP POLICY IF EXISTS "Alert family isolation" ON public.alerts;
CREATE POLICY "Alert family isolation" ON public.alerts
  FOR ALL USING (family_id = get_my_family_id());

-- 2. Vitals Policy
DROP POLICY IF EXISTS "Vitals family isolation" ON public.vitals_log;
CREATE POLICY "Vitals family isolation" ON public.vitals_log
  FOR ALL USING (family_id = get_my_family_id());

-- 3. Medications Policy
DROP POLICY IF EXISTS "Medication family isolation" ON public.medications;
CREATE POLICY "Medication family isolation" ON public.medications
  FOR ALL USING (family_id = get_my_family_id());

-- 4. Medication Logs Policy
DROP POLICY IF EXISTS "Med log family isolation" ON public.medication_logs;
CREATE POLICY "Med log family isolation" ON public.medication_logs
  FOR ALL USING (
    profile_id IN (SELECT id FROM public.profiles WHERE family_id = get_my_family_id())
  );

-- 5. Managed Devices Policy
DROP POLICY IF EXISTS "Device family isolation" ON public.managed_devices;
CREATE POLICY "Device family isolation" ON public.managed_devices
  FOR ALL USING (family_id = get_my_family_id());

-- Ensure pgnet is enabled for the webhook triggers
CREATE EXTENSION IF NOT EXISTS pgnet;
