-- MASTER SCHEMA RECOVERY & LOCKDOWN (HOTFIX V70.3)
-- Purpose: Repair Profiles table, create missing core tables, and enforce RLS.

-- ==========================================
-- PHASE 0: PROFILES TABLE REPAIR
-- ==========================================

-- 1. Ensure public.profiles exists
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid()
);

-- 2. Add missing columns to profiles if they don't exist
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='auth_id') THEN
    ALTER TABLE public.profiles ADD COLUMN auth_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='family_id') THEN
    ALTER TABLE public.profiles ADD COLUMN family_id UUID REFERENCES public.families(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='role') THEN
    ALTER TABLE public.profiles ADD COLUMN role TEXT CHECK (role IN ('familyHead', 'monitor', 'protected', 'minor'));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='first_name') THEN
    ALTER TABLE public.profiles ADD COLUMN first_name TEXT;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='is_managed') THEN
    ALTER TABLE public.profiles ADD COLUMN is_managed BOOLEAN DEFAULT false;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='fcm_token') THEN
    ALTER TABLE public.profiles ADD COLUMN fcm_token TEXT;
  END IF;
END $$;

-- ==========================================
-- PHASE 1: HELPER FUNCTION & CORE TABLES
-- ==========================================

-- Fixed: Correctly references 'auth_id' to match the authenticated user
CREATE OR REPLACE FUNCTION get_my_family_id() 
RETURNS UUID AS $$
  SELECT family_id FROM public.profiles WHERE auth_id = auth.uid() LIMIT 1;
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- Alerts
CREATE TABLE IF NOT EXISTS public.alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL,
  severity TEXT CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  status TEXT DEFAULT 'active',
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Vitals
CREATE TABLE IF NOT EXISTS public.vitals_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  heart_rate TEXT,
  blood_pressure TEXT,
  logged_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Medications
CREATE TABLE IF NOT EXISTS public.medications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  dosage TEXT,
  schedule TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Medication Logs
CREATE TABLE IF NOT EXISTS public.medication_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medication_id UUID REFERENCES public.medications(id) ON DELETE CASCADE NOT NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  taken_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  status TEXT DEFAULT 'taken'
);

-- Managed Devices
CREATE TABLE IF NOT EXISTS public.managed_devices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES public.families(id) ON DELETE CASCADE NOT NULL,
  assigned_profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  device_type TEXT NOT NULL,
  last_ping TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- PHASE 2: ROW LEVEL SECURITY (RLS)
-- ==========================================

ALTER TABLE public.families ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vitals_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medication_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.managed_devices ENABLE ROW LEVEL SECURITY;

-- Apply family-level isolation across all tables
DO $$ 
BEGIN
    -- Profiles
    DROP POLICY IF EXISTS "Profile family isolation" ON public.profiles;
    CREATE POLICY "Profile family isolation" ON public.profiles FOR ALL USING (family_id = get_my_family_id() OR auth_id = auth.uid());

    -- Alerts
    DROP POLICY IF EXISTS "Alert family isolation" ON public.alerts;
    CREATE POLICY "Alert family isolation" ON public.alerts FOR ALL USING (family_id = get_my_family_id());

    -- Vitals
    DROP POLICY IF EXISTS "Vitals family isolation" ON public.vitals_log;
    CREATE POLICY "Vitals family isolation" ON public.vitals_log FOR ALL USING (family_id = get_my_family_id());

    -- Medications
    DROP POLICY IF EXISTS "Medication family isolation" ON public.medications;
    CREATE POLICY "Medication family isolation" ON public.medications FOR ALL USING (family_id = get_my_family_id());

    -- Medication Logs
    DROP POLICY IF EXISTS "Med log family isolation" ON public.medication_logs;
    CREATE POLICY "Med log family isolation" ON public.medication_logs FOR ALL USING (
      profile_id IN (SELECT id FROM public.profiles WHERE family_id = get_my_family_id())
    );

    -- Devices
    DROP POLICY IF EXISTS "Device family isolation" ON public.managed_devices;
    CREATE POLICY "Device family isolation" ON public.managed_devices FOR ALL USING (family_id = get_my_family_id());
END $$;

-- Enable the PGNET extension for webhooks if not active
CREATE EXTENSION IF NOT EXISTS pgnet;
