-- NUCLEAR SCHEMA ALIGNMENT (HOTFIX V70.4)
-- Purpose: Force repair of every table missing the 'family_id' column and apply RLS.

-- ==========================================
-- PHASE 0: THE FORCED REPAIR
-- ==========================================

DO $$ 
BEGIN 
  -- 1. REPAIR PROFILES
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='family_id') THEN
    ALTER TABLE public.profiles ADD COLUMN family_id UUID REFERENCES public.families(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='auth_id') THEN
    ALTER TABLE public.profiles ADD COLUMN auth_id UUID REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='first_name') THEN
    ALTER TABLE public.profiles ADD COLUMN first_name TEXT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='is_authorized') THEN
    ALTER TABLE public.profiles ADD COLUMN is_authorized BOOLEAN DEFAULT false;
  ELSE
    ALTER TABLE public.profiles ALTER COLUMN is_authorized SET DEFAULT false;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='sub_role') THEN
    ALTER TABLE public.profiles ADD COLUMN sub_role TEXT;
  END IF;

  -- 2. REPAIR VITALS_LOG
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'vitals_log') THEN
    CREATE TABLE public.vitals_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vitals_log' AND column_name='family_id') THEN
    ALTER TABLE public.vitals_log ADD COLUMN family_id UUID REFERENCES public.families(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vitals_log' AND column_name='profile_id') THEN
    ALTER TABLE public.vitals_log ADD COLUMN profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
  END IF;

  -- 3. REPAIR ALERTS
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'alerts') THEN
    CREATE TABLE public.alerts (id UUID PRIMARY KEY DEFAULT gen_random_uuid());
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='alerts' AND column_name='family_id') THEN
    ALTER TABLE public.alerts ADD COLUMN family_id UUID REFERENCES public.families(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='alerts' AND column_name='profile_id') THEN
    ALTER TABLE public.alerts ADD COLUMN profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
  END IF;

  -- 4. REPAIR MEDICATIONS
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'medications') THEN
    CREATE TABLE public.medications (id UUID PRIMARY KEY DEFAULT gen_random_uuid());
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='medications' AND column_name='family_id') THEN
    ALTER TABLE public.medications ADD COLUMN family_id UUID REFERENCES public.families(id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='medications' AND column_name='profile_id') THEN
    ALTER TABLE public.medications ADD COLUMN profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE;
  END IF;

  -- 5. REPAIR MANAGED_DEVICES
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'managed_devices') THEN
    CREATE TABLE public.managed_devices (id UUID PRIMARY KEY DEFAULT gen_random_uuid());
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='managed_devices' AND column_name='family_id') THEN
    ALTER TABLE public.managed_devices ADD COLUMN family_id UUID REFERENCES public.families(id) ON DELETE CASCADE;
  END IF;
END $$;

-- ==========================================
-- PHASE 1: LOGIC RE-INITIALIZATION
-- ==========================================

-- FIXED: Use plpgsql and SET search_path to bypass RLS recursion in profiles.
CREATE OR REPLACE FUNCTION get_my_family_id() 
RETURNS UUID AS $$
DECLARE
  _family_id UUID;
BEGIN
  SELECT family_id INTO _family_id FROM public.profiles WHERE auth_id = auth.uid() LIMIT 1;
  RETURN _family_id;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public;

-- ==========================================
-- PHASE 2: SECURITY LOCKDOWN (RLS)
-- ==========================================

-- Ensure RLS is enabled everywhere
ALTER TABLE public.families ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vitals_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.managed_devices ENABLE ROW LEVEL SECURITY;

-- Apply fresh policies
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Family isolation" ON public.families;
    CREATE POLICY "Family isolation" ON public.families FOR ALL USING (id = get_my_family_id());

    DROP POLICY IF EXISTS "Profile isolation" ON public.profiles;
    DROP POLICY IF EXISTS "Profiles own access" ON public.profiles;
    DROP POLICY IF EXISTS "Profiles family access" ON public.profiles;
    
    -- Split policy to avoid infinite recursion
    CREATE POLICY "Profiles own access" ON public.profiles FOR ALL USING (auth_id = auth.uid());
    CREATE POLICY "Profiles family access" ON public.profiles FOR SELECT USING (family_id = get_my_family_id());

    DROP POLICY IF EXISTS "Vitals isolation" ON public.vitals_log;
    CREATE POLICY "Vitals isolation" ON public.vitals_log FOR ALL USING (family_id = get_my_family_id());

    DROP POLICY IF EXISTS "Alert isolation" ON public.alerts;
    CREATE POLICY "Alert isolation" ON public.alerts FOR ALL USING (family_id = get_my_family_id());

    DROP POLICY IF EXISTS "Medication isolation" ON public.medications;
    CREATE POLICY "Medication isolation" ON public.medications FOR ALL USING (family_id = get_my_family_id());

    DROP POLICY IF EXISTS "Device isolation" ON public.managed_devices;
    CREATE POLICY "Device isolation" ON public.managed_devices FOR ALL USING (family_id = get_my_family_id());
END $$;
