-- SUPABASE SCHEMA BLUEPRINT (BATCH A: ADVANCED MANAGEMENT & WRITE-BACK)
-- Use this version to support Medications, Logs, and dynamic Alerts.

-- 1. FAMILIES TABLE
CREATE TABLE IF NOT EXISTS families (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  invite_code TEXT UNIQUE NOT NULL, -- 6-digit alphanumeric
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  admin_id UUID NOT NULL REFERENCES auth.users(id)
);

-- 2. PROFILES TABLE
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  family_id UUID REFERENCES families(id) ON DELETE CASCADE,
  role TEXT CHECK (role IN ('familyHead', 'member', 'monitor', 'protected', 'minor')),
  sub_role TEXT, -- 'monitor', 'minor', 'protected'
  first_name TEXT NOT NULL,
  is_managed BOOLEAN DEFAULT false,
  is_authorized BOOLEAN DEFAULT false,
  status TEXT DEFAULT 'Stable',
  aura_color TEXT DEFAULT '0xFF0D9488',
  fcm_token TEXT, -- For Firebase Push Notifications
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. MEDICATIONS TABLE
CREATE TABLE IF NOT EXISTS medications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  family_id UUID REFERENCES families(id) ON DELETE CASCADE NOT NULL,
  name TEXT NOT NULL,
  dosage TEXT,
  schedule TEXT NOT NULL, -- e.g., '12:00 PM'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. MEDICATION LOGS
CREATE TABLE IF NOT EXISTS medication_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  medication_id UUID REFERENCES medications(id) ON DELETE CASCADE NOT NULL,
  taken_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  method TEXT DEFAULT 'button' -- 'button' or 'voice'
);

-- 5. ALERTS TABLE
CREATE TABLE IF NOT EXISTS alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  family_id UUID REFERENCES families(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL, -- 'fall', 'speeding', 'heart_rate', 'weather'
  message TEXT NOT NULL,
  severity TEXT CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  is_resolved BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. VITALS LOG
CREATE TABLE IF NOT EXISTS vitals_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  heart_rate TEXT,
  blood_pressure TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. MANAGED DEVICES
CREATE TABLE IF NOT EXISTS managed_devices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  family_id UUID REFERENCES families(id) ON DELETE CASCADE NOT NULL,
  assigned_profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  device_type TEXT NOT NULL,
  sync_status TEXT DEFAULT 'active',
  last_ping TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. RLS POLICIES (HARDENING)
ALTER TABLE families ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE medications ENABLE ROW LEVEL SECURITY;
ALTER TABLE medication_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE vitals_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE managed_devices ENABLE ROW LEVEL SECURITY;

-- Shared function for family_id check
-- FIXED: Added SECURITY DEFINER to bypass RLS recursion on the profiles table.
CREATE OR REPLACE FUNCTION public.get_auth_family_id() 
RETURNS UUID AS $$
BEGIN
  RETURN (
    SELECT family_id 
    FROM public.profiles 
    WHERE auth_id = auth.uid() 
    LIMIT 1
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public;

-- Families
DROP POLICY IF EXISTS "Users can view family" ON families;
DROP POLICY IF EXISTS "Family isolation" ON families;
CREATE POLICY "Family isolation" ON families 
  FOR ALL TO authenticated 
  USING (id = public.get_auth_family_id());

-- Profiles
DROP POLICY IF EXISTS "Users can manage family profiles" ON public.profiles;
DROP POLICY IF EXISTS "Profiles own access" ON public.profiles;
DROP POLICY IF EXISTS "Profiles family access" ON public.profiles;

-- Users can always see and manage their own profile (No recursion)
CREATE POLICY "Profiles own access" ON public.profiles
  FOR ALL TO authenticated
  USING (auth_id = auth.uid())
  WITH CHECK (auth_id = auth.uid());

-- Users can see others in the same family (Uses non-recursive helper)
CREATE POLICY "Profiles family access" ON public.profiles
  FOR SELECT TO authenticated
  USING (family_id = public.get_auth_family_id());

-- Medications
DROP POLICY IF EXISTS "Users can manage family medications" ON medications;
DROP POLICY IF EXISTS "Medication isolation" ON medications;
CREATE POLICY "Medication isolation" ON medications 
  FOR ALL TO authenticated 
  USING (family_id = public.get_auth_family_id());

-- Medication Logs
DROP POLICY IF EXISTS "Users can view family med logs" ON medication_logs;
DROP POLICY IF EXISTS "Med log isolation" ON medication_logs;
CREATE POLICY "Med log isolation" ON medication_logs 
  FOR ALL TO authenticated 
  USING (
    profile_id IN (
      SELECT id FROM public.profiles 
      WHERE family_id = public.get_auth_family_id()
    )
  );

-- Alerts
DROP POLICY IF EXISTS "Users can manage family alerts" ON alerts;
DROP POLICY IF EXISTS "Alert isolation" ON alerts;
CREATE POLICY "Alert isolation" ON alerts 
  FOR ALL TO authenticated 
  USING (family_id = public.get_auth_family_id());

-- Vitals
DROP POLICY IF EXISTS "Users can manage family vitals" ON vitals_log;
DROP POLICY IF EXISTS "Vitals isolation" ON vitals_log;
CREATE POLICY "Vitals isolation" ON vitals_log 
  FOR ALL TO authenticated 
  USING (
    profile_id IN (
      SELECT id FROM public.profiles 
      WHERE family_id = public.get_auth_family_id()
    )
  );

-- Devices
DROP POLICY IF EXISTS "Users can manage family devices" ON managed_devices;
DROP POLICY IF EXISTS "Device isolation" ON managed_devices;
CREATE POLICY "Device isolation" ON managed_devices 
  FOR ALL TO authenticated 
  USING (family_id = public.get_auth_family_id());
